const paras =[
    `Researchers at the Heidelberg University Hospital conducted a study in which they subjected a young doctor to a job interview, which they made even more stressful by forcing him to solve complex math problems for thirty minutes. Afterward, they took a blood sample. What they discovered was that his antibodies had reacted to stress the same way they react to pathogens, activating the proteins that trigger an immune response. The problem is that this response not only neutralizes harmful agents, it also damages healthy cells, leading them to age prematurely.`,
    `By his mid 40s Gupta was CEO of McKinsey, the world's most prestigious consulting firm. He retired in 2007 to take on roles with the United Nations and the World Economic Forum. He partnered on philanthropic work with Bill Gates. He sat on the board of directors of five public companies. From the slums of Kolkata, Gupta had quite literally become one of the most successful businessmen alive.`,
    `LIFE’S AMAZING SECRETS Gaur Gopal Das studied electrical engineering from the College of Engineering, Pune. After a brief stint with Hewlett Packard, he decided to live as a monk in an ashram in downtown Mumbai. He has remained there for twenty-two years, learning the antiquity of ancient philosophy and the modernity of contemporary psychology, to become a life coach to thousands in the city. Gaur Gopal Das has been travelling the world since 2005, sharing his wisdom with corporate executives, universities and charities. In 2016, his global popularity exploded as he took his message online. With millions of views on his videos on social media, he has now begun to lead a movement to help others achieve happiness and purpose in their lives. Now one of the most famous monks in the world, Gaur Gopal Das holds the title of ‘The Ideal Young Spiritual Guru’, conferred upon him by the Indian Student Parliament, MIT Pune.`,
    `Cat gets stuck in tree firefighters try to get cat down firefighters get stuck in tree cat eats firefighters' slippers kitty power ignore the squirrels, you'll never catch them anyway for what a cat-ass-trophy! or purr as loud as possible, be the most annoying cat that you can, and, knock everything off the table. Pretend you want to go out but then don't bite off human's toes, yet disappear for four days and return home with an expensive injury; bite the vet so catch eat throw up catch eat throw up bad birds. `,
  `This opera's as lousy as it is brilliant! Your lyrics lack subtlety. You can't just have your characters announce how they feel. That makes me feel angry! Anyhoo, your net-suits will allow you to experience Fry's worm infested bowels as if you were actually wriggling through them. I just told you! You've killed me! Fry! Quit doing the right thing, you jerk! Michelle, I don't regret this, but I both rue and lament it. Morbo can't understand his teleprompter because he forgot how you say that letter that's shaped like a man wearing a hat.`,
  `Airedale hard cheese mozzarella. Pecorino melted cheese port-salut emmental babybel cheese and wine melted cheese manchego. Everyone loves blue castello everyone loves fromage cheese slices airedale cheddar cream cheese. Bavarian bergkase who moved my cheese halloumi port-salut gouda jarlsberg ricotta rubber cheese. Stinking bishop smelly cheese brie.`,
  `Salvia glossier subway tile, leggings mustache YOLO semiotics chia. Pitchfork tbh af blog church-key meggings vaporware PBR&B master cleanse post-ironic man bun pabst mustache letterpress synth. Snackwave raw denim godard, 3 wolf moon shaman offal kitsch unicorn live-edge selvage schlitz fashion axe vaporware drinking vinegar prism. Shabby chic tacos artisan, chambray chicharrones cardigan leggings typewriter af pop-up williamsburg meditation PBR&B viral. You probably haven't heard of them DIY jean shorts subway tile fashion axe bushwick kitsch tumeric cloud bread vaporware freegan franzen pork belly chicharrones banh mi.`,
  `Man braid celiac synth freegan readymade, pitchfork fam salvia waistcoat lomo bitters gentrify four loko. Pitchfork semiotics post-ironic vegan. Tofu meditation microdosing hashtag semiotics venmo. Flexitarian vape tilde taiyaki. Prism poutine farm-to-table, messenger bag vegan taxidermy tattooed sartorial squid jean shorts fixie selvage trust fund vape.`,
  `Rutters Plate Fleet boom chandler Brethren of the Coast handsomely lookout marooned brigantine knave. Buccaneer gangway jack rum loot spyglass line Jack Tar fore gaff. Gaff topmast scuttle ballast swab draught measured fer yer chains dance the hempen jig Chain Shot yardarm.`,

]

export default paras;
